'use client';

import { DataLabel, DataSource } from '@/lib/types';
import { useState } from 'react';
import { Info, X, ExternalLink } from 'lucide-react';
import clsx from 'clsx';

interface DataProvenanceProps {
  value: string | number;
  label: DataLabel;
  source: DataSource;
  sourceUrl?: string;
  lastUpdated?: string;
  notes?: string;
  unit?: string;
  className?: string;
}

const LABEL_CONFIG: Record<DataLabel, { color: string; bg: string; border: string; description: string }> = {
  OBSERVED: {
    color: 'text-emerald-400',
    bg: 'bg-emerald-400/8',
    border: 'border-emerald-400/30',
    description: 'Data directly obtained from a public authoritative source.',
  },
  DERIVED: {
    color: 'text-blue-400',
    bg: 'bg-blue-400/8',
    border: 'border-blue-400/30',
    description: 'Value mathematically calculated from observed public data (e.g., orbital elements).',
  },
  AI: {
    color: 'text-purple-400',
    bg: 'bg-purple-400/8',
    border: 'border-purple-400/30',
    description: 'Analysis, classification, or explanation generated by ORBITAL\'s AI layer.',
  },
  ESTIMATED: {
    color: 'text-amber-400',
    bg: 'bg-amber-400/8',
    border: 'border-amber-400/30',
    description: 'Approximate value based on typical mission parameters. Treat with caution.',
  },
};

const SOURCE_URLS: Record<DataSource, string> = {
  NASA: 'https://www.nasa.gov',
  CelesTrak: 'https://celestrak.org',
  SatNOGS: 'https://db.satnogs.org',
  ESA: 'https://www.esa.int',
  JAXA: 'https://www.jaxa.jp',
  ISRO: 'https://www.isro.gov.in',
  CNSA: 'https://www.cnsa.gov.cn',
  AI: '',
};

export function DataProvenance({
  value,
  label,
  source,
  sourceUrl,
  lastUpdated,
  notes,
  unit,
  className,
}: DataProvenanceProps) {
  const [open, setOpen] = useState(false);
  const cfg = LABEL_CONFIG[label];

  return (
    <div className={clsx('relative inline-flex items-center gap-1', className)}>
      <span className="text-orbit-white font-mono text-sm">
        {value}
        {unit && <span className="text-orbit-dim text-xs ml-1">{unit}</span>}
      </span>
      <button
        onClick={() => setOpen(!open)}
        className={clsx(
          'inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[9px] tracking-widest border font-medium transition-colors',
          cfg.color, cfg.bg, cfg.border
        )}
      >
        {label}
        <Info size={8} className="ml-0.5" />
      </button>

      {open && (
        <div className="absolute bottom-full left-0 mb-2 z-50 w-64 glass rounded-lg p-3 shadow-2xl border border-space-border animate-fade-in">
          <div className="flex items-start justify-between gap-2 mb-2">
            <div className={clsx('text-[10px] font-semibold tracking-widest', cfg.color)}>{label}</div>
            <button onClick={() => setOpen(false)}>
              <X size={11} className="text-orbit-dim hover:text-orbit-white" />
            </button>
          </div>
          <p className="text-[11px] text-orbit-dim leading-relaxed mb-2">{cfg.description}</p>
          <div className="space-y-1 pt-2 border-t border-space-border">
            <div className="flex items-center justify-between">
              <span className="text-[9px] text-orbit-dim tracking-wider">SOURCE</span>
              <span className="text-[11px] text-orbit-white font-medium">{source}</span>
            </div>
            {lastUpdated && (
              <div className="flex items-center justify-between">
                <span className="text-[9px] text-orbit-dim tracking-wider">UPDATED</span>
                <span className="text-[11px] text-orbit-dim">{lastUpdated}</span>
              </div>
            )}
            {notes && (
              <p className="text-[10px] text-orbit-dim/70 mt-1 leading-relaxed">{notes}</p>
            )}
            {(sourceUrl || SOURCE_URLS[source]) && (
              <a
                href={sourceUrl || SOURCE_URLS[source]}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1 text-[10px] text-orbit-blue hover:text-orbit-accent mt-1"
              >
                <ExternalLink size={9} />
                View source
              </a>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

interface DataSourcePanelProps {
  sources: Array<{ source: DataSource; description: string; url?: string; dataset?: string }>;
}

export function DataSourcePanel({ sources }: DataSourcePanelProps) {
  return (
    <div className="glass rounded-lg p-4 space-y-3">
      <div className="text-[10px] text-orbit-dim tracking-widest pb-2 border-b border-space-border">DATA SOURCES</div>
      {sources.map((s, i) => (
        <div key={i} className="flex items-start gap-3">
          <div className="w-16 shrink-0">
            <div className="text-[11px] text-orbit-white font-medium">{s.source}</div>
          </div>
          <div className="flex-1">
            <div className="text-[11px] text-orbit-dim leading-relaxed">{s.description}</div>
            {s.dataset && <div className="text-[10px] text-orbit-dim/60 mt-0.5">{s.dataset}</div>}
          </div>
          {(s.url || SOURCE_URLS[s.source]) && (
            <a
              href={s.url || SOURCE_URLS[s.source]}
              target="_blank"
              rel="noopener noreferrer"
              className="shrink-0 text-orbit-blue/60 hover:text-orbit-blue"
            >
              <ExternalLink size={12} />
            </a>
          )}
        </div>
      ))}
    </div>
  );
}

export function DataLegend() {
  return (
    <div className="flex flex-wrap gap-2">
      {(Object.keys(LABEL_CONFIG) as DataLabel[]).map((label) => {
        const cfg = LABEL_CONFIG[label];
        return (
          <div
            key={label}
            className={clsx(
              'flex items-center gap-1.5 px-2 py-1 rounded border text-[10px] tracking-widest',
              cfg.color, cfg.bg, cfg.border
            )}
          >
            {label}
          </div>
        );
      })}
    </div>
  );
}
